nohup python launch_config_save.py sobel_small hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_sobel_small.out &
wait 
nohup python launch_config_save.py superpixel_fcn hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_superpixel_fcn.out &
