nohup python launch_config_save.py halftone_gray hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_halftone_gray.out &
wait
nohup python launch_config_save.py grayscale hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_grayscale.out &
