nohup python launch_config_save.py normals_xtc hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_normals_xtc.out &
wait
nohup python launch_config_save.py edges_dexined hypersim_v2_template_save_iter1_v3.ini > logs_hypersim_v2_save_iter1_v3_edges_dexined.out &
